#!/bin/bash

default=n
prompt=

usage() {
  echo "Usage: yn [-y|-n] [prompt]"
  echo "  -y           Default yes"
  echo "  -n           Default no (default)"
  echo "  prompt       The prompt to display"
  exit 0
}

while [ "$1" ]; do
  case "$1" in
  -h | --help)
    usage
    ;;
  -y)
    default=y
    shift
    ;;
  -n)
    default=n
    shift
    ;;
  *)
    prompt="$1"
    shift
    ;;
  esac
done

if [ "$default" = y ]; then
  prompt="$prompt [Y/n]: "
else
  prompt="$prompt [y/N]: "
fi

read -r -n 1 -p "$prompt" answer
echo

case "${answer:-$default}" in
[Yy]*) exit 0 ;;
[Nn]*) exit 1 ;;
*) exit 1 ;;
esac
