#!/bin/zsh

default=n
prompt=

while [ "$1" ]; do
  case "$1" in
    -y)
      default=y
      shift
      ;;
    -n)
      default=n
      shift
      ;;
    *)
      prompt="$1"
      shift
      ;;
  esac
done

[ "$default" = y ] && prompt="$prompt [Y/n]: " || prompt="$prompt [y/N]: "
read -q "?$prompt" answer
echo
case "${answer:-$default}" in
  [Yy]*) exit 0 ;;
  [Nn]*) exit 1 ;;
  *) exit 1 ;;
esac
