background #011423
foreground #cbe0f0

cursor #47ff9c

color0 #214969
color1 #db4b4c
color2 #44ffb1
color3 #ffe073
color4 #0fc5ed
color5 #a277ff
color6 #24eaf7
color7 #e6eaf2

color8 #2d5b86
color9 #e5625e
color10 #5cffce
color11 #ffe78f
color12 #26c7f0
color13 #b38eff
color14 #36f0ff
color15 #f0f4ff

selection_background #033259
selection_foreground #cbe0f0

active_border_color #24eaf7
inactive_border_color #808080

tab_bar_background #011423
